export const ACCESS_CODE = {
    ADMIN : "ADM-SUP",
    CLIENT: "USR-CLI",
    PERSONNEL: "USR-PER",
    PERSONNEL_PEERS: "USR-PPR",
    MANAGEMENT_UJI: "MNG-UJI",
    MANAGEMENT_KAL: "MNG-KAL",
    KEPALA_LAB: "HED-LAB"
}