export const jenisAlatKalibrasi = [
    "Keselamatan Listrik",
    "Perhitungan Ketidakpastian",
    "Anak Timbangan ",
    "Analitical Balance",
    "Anesthesi Ventilator",
    "Anesthesi Unit",
    "Audiometer",
    "Auto Refrakto Keratometer (ARK)",
    "Autoclave",
    "Autorefrakto",
    "Inkubator Bayi",
    "Bed Side Monitor (Pasien Monitor)",
    "Blood Bank Refrigerator",
    "Blood Pressure Monitor (Tensi Digital)",
    "Cardiotocograph",
    "Centrifuge",
    "CPAP",
    "Defibrilator",
    "Digital Manometer",
    "Electrocardiograph (ECG)",
    "Electroenchepalograph (EEG)",
    "Electrosimulator",
    "Electro Surgery Unit (ESU)",
    "Fetal Doppler",
    "Flowmeter",
    "Infant Warmer",
    "Infusion Pump",
    "Inkubator Laboratorium",
    "Lampu Operasi",
    "Luxmeter",
    "Medical Freezer",
    "Medical Refrigerator",
    "Mikroskop",
    "Nebulizer",
    "Oven",
    "Oxygen Concentrator",
    "Phototerapi",
    "Platelet Agitator Inkubator",
    "Rotator",
    "Pulse Oxymeter",
    "Sphygmomanometer",
    "Spirometer",
    "Sterilisator",
    "Stirrer",
    "Suction Pump",
    "Syringe Pump",
    "Tachometer",
    "Thermohygrometer",
    "Thermometer ",
    "Timbangan Bayi",
    "Auto Non Contact Tonometer (NCT)",
    "Traksi",
    "Treadmill ECG",
    "Computed Radiography",
    "CT Scan",
    "Dental Panoramic",
    "Dental Xray",
    "Digital Radiography",
    "Fluoroscopy",
    "General Xray",
    "Mammography",
    "Xray Mobile",
    "MRI",
    "Ultrasonography (USG)",
    "Ultrasound Therapy",
    "Ultraviolet Sterilizer",
    "Anesthesi Vaporizer",
    "Ventilator",
    "Waterbath",
    "Xray Angiography",
    "Automatic Chemistry Analyzer",
    "Auto Keratometer",
    "Automatic External Defribilator (AED)",
    "Baby Incubator Transport",
    "Bio Safety Cabinet",
    "Blood Solution Warmer",
    "Bone Mass Densitometer",
    "Central Monitor",
    "Centrifuge Refrigerator",
    "Chamber Audiometer",
    "Cold Chain",
    "Defribrilator with Monitor",
    "Xray Panoramic Chepalometri",
    "Dental Unit",
    "Digital Radiography Mobile",
    "Dosimeter Perorangan Gamma",
    "Echocardiograph",
    "Electrical Safety Analyzer (ESA)",
    "Electrical Surgery Analyzer ",
    "Electro Accupuncture",
    "Electro Convulsive Teraphy (ECT)",
    "Electro Stimulator With Vacuum Electrodes",
    "Electrocardiograph Simulator",
    "Electromiograph (EMG)",
    "Endoscopic Light",
    "ENT Treatment",
    "ESWL",
    "Examination Lamp (Lampu Tindakan)",
    "Hemodialisa",
    "Hematologi Analyzer",
    "Humidifier",
    "Infusion Device Analyzer",
    "Injector Syringe",
    "Laminary Air Flow",
    "Laryngoscope",
    "Light Source",
    "Micropipete Multi Channel",
    "Micropipete Fix Volume",
    "Operating Mikroskop Mata",
    "Operating Mikroskop Syaraf",
    "Operating Mikroskop ENT",
    "Otoscope",
    "Parafin Bath",
    "PH Meter",
    "Photometer",
    "Photometer Semi Automatic",
    "Pipet Volume",
    "Pneumatic Tourniquet",
    "Red Lamp Theraphy",
    "Resusitasi Paru",
    "Spectrophotometer",
    "Strees Test (Treadmill + ECG + NIBP)",
    "Surveimeter Gamma",
    "Pembacaan TLD Hp (10)",
    "Thermometer Infrared",
    "Timbangan Dewasa",
    "Timbangan Darah",
    "Timbangan Analitik Mekanik Dua Lengan",
    "Tymponometry",
    "Ventilator Anesthesi",
    "Ventilator Transport",
    "Gas Medik" 
]